%% UU - Kapitein Lab
% Analyze in vitro single molecule motility assays
% MKI and CC 2019-11-05
%% This code reads in the files generated by post_particle_tracking_1 for one condition.
% To use this file you will need the following files:
%
%
%
%
%% Options (make 0 to NOT perform related action, 1 to perform)
zplot = 0;
zsave = 0;

%% Parameters
pixel_size = 64.6; %[nm]
exp_time = 0.1; %[s]
min_rl = 150; %[nm]

%% Read in data


%% Save data
if zsave ~= 0
    
end